### ISSUE TITLE
Volume Mapping: Internal Path?

### ISSUE THREAD

**Issue by SteveASky** [mbentley/docker-kimchi#2]
Hi Matt. Quick question, on the instantiation line, you have a volume mapped:

-v /path/to/your/storage:/path/to/your/storage \

I think the second part should map internally to the container (I guess either /etc/kimchi or /kimchi). 

Which should it be, or am I misunderstanding?

**Comment by mbentley** [comment]
It is like /var/lib/libvirt/images so kimchi can access your virtual disk storage.  It should be the same path inside and outside of the container.

**Comment by SteveASky** [comment]
Ah of course, got it. Thanks for the clarification Matt.
